name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull latest base images
        run: |
          docker pull postgres:latest
          docker pull dpage/pgadmin4:latest

      - name: Build the Docker images
        run: docker-compose build

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Docker images
        run: |
          docker tag postgres ${{ secrets.DOCKER_USERNAME }}/scrum-user-postgres:1.0
          docker tag dpage/pgadmin4 ${{ secrets.DOCKER_USERNAME }}/scrum-user-pgadmin:1.0
          docker tag docker-scrum-and-user-spring-boot-scrum ${{ secrets.DOCKER_USERNAME }}/spring-boot-scrum:1.0
          docker tag docker-scrum-and-user-spring-boot-user ${{ secrets.DOCKER_USERNAME }}/spring-boot-user:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/scrum-user-postgres:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/scrum-user-pgadmin:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-scrum:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot-user:1.0

      - name: Deploy with docker-compose
        run: docker-compose up -d
